
# Starship configuration for Linux

format = """
[‚ï≠‚îÄ](bold green)$os$username$hostname$directory$git_branch$git_status$python$nodejs$rust$golang$java
[‚ï∞‚îÄ](bold green)$character"""

right_format = """$cmd_duration$time"""

[character]
success_symbol = "[‚ûú](bold green)"
error_symbol = "[‚ûú](bold red)"

[os]
format = "[$symbol](bold blue)"
disabled = false

[os.symbols]
Linux = "üêß"

[username]
format = "[$user]($style)@"
style_user = "bold blue"
show_always = true

[hostname]
format = "[$hostname]($style) "
style = "bold blue"
ssh_only = false

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "on [$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"

[nodejs]
format = "[$symbol($version )]($style)"
style = "bold green"

[rust]
format = "[$symbol($version )]($style)"
style = "bold red"

[golang]
format = "[$symbol($version )]($style)"
style = "bold cyan"

[java]
format = "[$symbol($version )]($style)"
style = "bold red"

[cmd_duration]
format = " took [$duration]($style)"
style = "bold yellow"
min_time = 2000

[time]
format = "[$time]($style)"
style = "bold white"
disabled = false
